name: Clone Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clone_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo_name: [blog2, blog3, blog4, blog5, blog6, blog7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone and rename repository
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.TOKEN }}@github.com/Craftguy-Billies/blog1.git ${{ matrix.repo_name }}
          cd ${{ matrix.repo_name }}
          git remote remove origin
          git remote add origin https://$GITHUB_ACTOR:${{ secrets.TOKEN }}@github.com/Craftguy-Billies/${{ matrix.repo_name }}.git
          git push -u origin main --force
